name: Dev-terraform-infra-workflow 

on:
  workflow_dispatch:

permissions:
  id-token: write      
  contents: read 

jobs:
  terraform-init-plan:       
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init
        working-directory: ./Env/Dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./Env/Dev

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./Env/Dev

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./Env/Dev

