name: terraform infra-Pipleine

on: workflow_dispatch
   
jobs:
  Terraforminit:
    name: Terraform init
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
      
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
          terraform_version: 1.6.6 
    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform Validate
      
    - name: Terraform Plan
      run: terraform Plan
  
     
          
          
