name: terra-infra

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read 

jobs:
  terraform-init-plan:
    runs-on: ubuntu-latest
    name: terraform init and plan
    
    steps:
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init -input=false

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
