name: 'Terraform'

on: workflow_dispatch

permissions:
  id-token: write      
  contents: read 

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Azure Login
      uses: azure/login@v2.3.0         
      with:
        creds: |
          {
            "clientId": "${{ secrets.ARM_CLIENT_ID }}",
            "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.ARM_TENANT_ID }}", 
            }

      

  
    - name: Terraform Init
      run: terraform init
      working-directory: ./Env/Dev   
   
    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ./Env/Dev   
  
    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: ./Env/Dev   
      
    - name: Terraform Apply
      if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
      working-directory: ./Env/Dev   
