name: 'Terraform'

on: workflow_dispatch

permissions:
  id-token: write      
  contents: read 

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    
    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4
      
      # Azure Login using Service Principal (creds JSON)
      - name: Azure Login
        uses: azure/login@v2.3.0
        with: ${{ secrets.ARM_CLIENT_ID }}
          

      # Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./Env/Dev   

      # Terraform Format Check
      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ./Env/Dev   

      # Terraform Plan
      - name: Terraform Plan
        run: terraform p
